# -*- coding: utf-8 -*-

"""
/***************************************************************************
 KORTxyz
                                 A QGIS plugin
 KORTxyz ProcessingTool 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-10-13
        copyright            : (C) 2025 by Tino Kastbjerg Stigsen
        email                : info@kort.xyz
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Tino Kastbjerg Stigsen'
__date__ = '2025-10-13'
__copyright__ = '(C) 2025 by Tino Kastbjerg Stigsen'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

import os
import sys
import inspect

# --- QGIS imports ---
from qgis.core import QgsSettings, QgsApplication
from qgis.gui import QgsOptionsPageWidget, QgsOptionsWidgetFactory

# --- PyQt imports ---
from qgis.PyQt.QtWidgets import (
    QHBoxLayout, QVBoxLayout, QLabel, QLineEdit, QPushButton
)
from qgis.PyQt.QtGui import QIcon, QDesktopServices
from qgis.PyQt.QtCore import QUrl

# --- Local import ---
from .kortxyz_provider import KORTxyzProvider

# --- Ensure module path ---
cmd_folder = os.path.split(inspect.getfile(inspect.currentframe()))[0]
if cmd_folder not in sys.path:
    sys.path.insert(0, cmd_folder)


# --- Options Factory ---
class MyPluginOptionsFactory(QgsOptionsWidgetFactory):
    def __init__(self):
        super().__init__()

    def icon(self):
        icon_path = os.path.join(os.path.dirname(__file__), 'icon.svg')
        return QIcon (icon_path)
    
    def createWidget(self, parent):
        return ConfigOptionsPage(parent)
    
# --- Options Page ---
class ConfigOptionsPage(QgsOptionsPageWidget):
    def __init__(self, parent):
        super().__init__(parent)

        layout = QVBoxLayout()
        layout.setContentsMargins(6, 6, 6, 6)

        label = QLabel("<b>Datafordeler API KEY</b>")

        hbox = QHBoxLayout()
        self.df_api_key_edit = QLineEdit()
        self.df_api_key_edit.setPlaceholderText("<API-Key>")
        self.generate_btn = QPushButton("Fetch APIKEY…")

        hbox.addWidget(self.df_api_key_edit)
        hbox.addWidget(self.generate_btn)

        layout.addWidget(label)
        layout.addLayout(hbox)
        layout.addStretch()
        self.setLayout(layout)

        self.generate_btn.clicked.connect(self.generate_token)
        self.reset()

    def generate_token(self):
        QDesktopServices.openUrl(QUrl("https://portal.datafordeler.dk/it-systemer"))

    def apply(self):
        s = QgsSettings()
        s.setValue("KORTxyz/df_api_key", self.df_api_key_edit.text())

    def reset(self):
        s = QgsSettings()
        self.df_api_key_edit.setText(s.value("KORTxyz/df_api_key", ""))



# --- Main Plugin Class ---
class KORTxyzPlugin:
    def __init__(self, iface):
        self.iface = iface
        self.provider = None
        self.options_factory = None
    
    def initProcessing(self):
        reg = QgsApplication.processingRegistry()

        # Remove any previous instances (Fix for Plugin Reloader)
        old = reg.providerById("KORTxyz")
        if old:
            reg.removeProvider(old)

        # Add fresh provider
        self.provider = KORTxyzProvider()
        reg.addProvider(self.provider)

    def initGui(self):
        self.initProcessing()

        # Options page
        self.options_factory = MyPluginOptionsFactory()
        self.options_factory.setTitle('KORTxyz')

        if hasattr(self.iface, 'registerOptionsWidgetFactory'):
            self.iface.registerOptionsWidgetFactory(self.options_factory)
        else:
            from qgis.gui import QgsGui
            QgsGui.instance().registerOptionsWidgetFactory(self.options_factory)

    def unload(self):
        # Remove UI components
        if self.options_factory:
            if hasattr(self.iface, 'unregisterOptionsWidgetFactory'):
                self.iface.unregisterOptionsWidgetFactory(self.options_factory)
            else:
                from qgis.gui import QgsGui
                QgsGui.instance().unregisterOptionsWidgetFactory(self.options_factory)

            self.options_factory = None

        # Remove processing provider
        reg = QgsApplication.processingRegistry()
        if self.provider:
            reg.removeProvider(self.provider)
            self.provider = None
